# CONFIGURATION FILE FOR WARP-PLUS-FLASK

# ENABLE PROXY (BYPASS CLOUDFLARE BLOCK)
proxy_enabled = False

# CUSTOM STATIC PROXY (PROXY_ENABLED MUST BE TRUE)
# PROXY MUST SUPPORT CUSTOM HEADER AND POST REQUEST. TESTED WITH HTTP PROTOCOL.
# LEAVE BLANK TO USE GETPROXYLIST.COM
# custom_proxy = {"host": "144.91.82.190:3128", "protocol": "http"} 
custom_proxy = {}


# SET MAXIMUM NUMBER OF RETRY IF REQUEST IS FAILED
max_retry = 5